### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\nboch_000\AppData\Local\atom\a...

### ISSUE THREAD

**Issue by sh1ny** [subesokun/atom-tree-view-git-status#11]
[Enter steps to reproduce below:]
1. Open atom
2. File -> Settings.

It always triggers the same error. When the error is already thrown, you can do File->Settings and settings properly come up.

**Atom Version**: 1.0.11
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) package, v0.2.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\nboch_000\AppData\Local\atom\app-1.0.11\atom:'

```
At ATOM_SHELL_ASAR.js:50

Error: ENOENT: no such file or directory, lstat 'C:\Users\nboch_000\AppData\Local\atom\app-1.0.11\atom:'
  at Error (native)
  at fs.lstatSync (fs.js:836:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:170:16)
  at Object.realpathSync (fs.js:1439:21)
  at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:243:29)
  at Object.module.exports.TreeViewGitStatus.normalizePath (C:\Users\nboch_000\.atom\packages\tree-view-git-status\lib\main.coffee:293:15)
  at Object.module.exports.TreeViewGitStatus.updateRoots (C:\Users\nboch_000\.atom\packages\tree-view-git-status\lib\main.coffee:194:21)
  at C:\Users\nboch_000\.atom\packages\tree-view-git-status\lib\main.coffee:149:10
  at Emitter.module.exports.Emitter.emit (C:\Users\nboch_000\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Project.module.exports.Project.addPath (C:\Users\nboch_000\AppData\Local\atom\app-1.0.11\resources\app.asar\src\project.js:279:29)
  at EventEmitter.<anonymous> (C:\Users\nboch_000\AppData\Local\atom\app-1.0.11\resources\app.asar\src\window-event-handler.js:41:32)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "adventurous-syntax"
    ],
    "ignoredNames": [
      ".pyc"
    ],
    "openEmptyEditorOnStart": false
  }
}
```
### Installed Packages

``` coffee
# User
adventurous-syntax, v0.2.0
atom-django, v0.3.0
atom-minify, vundefined
autocomplete-python, v0.5.3
autocomplete-ruby, v0.1.0
clipboard-plus, v0.5.1
color-picker, v2.0.11
django-templates, v0.5.0
file-icons, v1.6.9
hashrocket, v0.4.8
imdone-atom, v1.1.38
jsonlint, v1.1.2
language-puppet, v0.14.0
linter, v1.5.2
linter-puppet-lint, v0.6.1
linter-ruby, v1.1.1
minimap, v4.13.3
nucleus-dark-ui, v0.4.5
pigments, v0.15.0
project-manager, v2.5.1
regex-railroad-diagram, v0.10.3
save-session, v0.15.7
slack-chat, v3.2.10
sync-settings, v0.6.0
tree-view-git-status, v0.2.0

# Dev
No dev packages
```

**Comment by subesokun** [comment]
Hi @sh1ny, sorry for the issues. Patch is on its way :bug:

Probably same issue as in #9

**Comment by subesokun** [comment]
Bug should be fixed by now. Please update let me know if you've still issues.

**Comment by sh1ny** [comment]
All fixed. You can close this. Thanks a lot !

**Comment by subesokun** [comment]
Sure, you're welcome :) Also thanks for reporting it!
