### ISSUE TITLE
Uncaught Error: Repository has been destroyed

### ISSUE THREAD

**Issue by Maelstromeous** [subesokun/atom-tree-view-git-status#12]
[Enter steps to reproduce below:]
1. Simply opened up atom

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.5
**Thrown From**: [tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) package, v0.2.1
### Stack Trace

Uncaught Error: Repository has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:382

Error: Repository has been destroyed
  at GitRepository.module.exports.GitRepository.getRepo (/Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:382:15)
  at GitRepository.module.exports.GitRepository.getConfigValue (/Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:193:19)
  at GitRepository.module.exports.GitRepository.getOriginURL (/Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:197:19)
  at TreeViewGitStatusTooltip.module.exports.TreeViewGitStatusTooltip.generateTooltipContent (/Users/Matt/.atom/packages/tree-view-git-status/lib/tooltip.coffee:30:5)
  at TreeViewGitStatusTooltip.module.exports.TreeViewGitStatusTooltip.onMouseEnter (/Users/Matt/.atom/packages/tree-view-git-status/lib/tooltip.coffee:68:15)
  at HTMLDivElement.<anonymous> (/Users/Matt/.atom/packages/tree-view-git-status/lib/tooltip.coffee:11:55)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-objective-c",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-go",
      "language-java",
      "language-mustache",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "linter-htmlhint"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
SFTP-deployment, v1.0.2
aligner, v0.16.1
aligner-css, v1.2.0
aligner-php, v1.0.0
atom-beautify, v0.28.12
autoclose-html, v0.19.0
autocomplete-paths, v1.0.2
color-picker, v2.0.11
css-color-underline, v1.0.1
css-snippets, v0.8.0
docblockr, v0.7.3
editor-stats, v0.17.0
file-icons, v1.6.9
highlight-line, v0.11.0
highlight-selected, v0.10.1
indent-guide-improved, v1.4.3
jquery-snippets, v11.0.0
jshint, v1.7.0
line-ending-converter, v1.3.2
linter, v1.6.0
linter-jsonlint, v1.0.1
linter-php, v1.0.3
minimap, v4.13.3
minimap-color-highlight, v4.1.4
minimap-highlight-selected, v4.3.0
minimap-pigments, v0.1.6
php-twig, v4.0.0
pigments, v0.15.0
pretty-json, v0.4.1
remote-sync, v3.1.2
sync-settings, v0.6.0
tab-control, v0.6.8
trailing-spaces, v0.3.2
tree-view-git-status, v0.2.1

# Dev
No dev packages
```

**Comment by subesokun** [comment]
Hi @Maelstrome26! Mhh this is a strange error. Either Atom fails to get the repository for the path you're trying to open or Atom did destroy for some reason the repository. Do you've this issue with any Git project you're trying to open with Atom or only with a special one? Can you please confirm that e.g. calling "git status" in that Git project folder gives you a valid output?
