### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by xuchen81** [subesokun/atom-tree-view-git-status#26]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.3
**Thrown From**: [tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) package, v0.2.3
### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At /Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at Object.module.exports.TreeViewGitStatus.isRepoModified (/Users/chen.xu/.atom/packages/tree-view-git-status/lib/main.coffee:370:21)
    at Object.module.exports.TreeViewGitStatus.doUpdateRootNode (/Users/chen.xu/.atom/packages/tree-view-git-status/lib/main.coffee:308:29)
    at /Users/chen.xu/.atom/packages/tree-view-git-status/lib/main.coffee:293:30
    at Map.forEach (native)
    at Object.module.exports.TreeViewGitStatus.updateRootForRepo (/Users/chen.xu/.atom/packages/tree-view-git-status/lib/main.coffee:287:38)
    at /Users/chen.xu/.atom/packages/tree-view-git-status/lib/main.coffee:241:24
    at Function.module.exports.Emitter.simpleDispatch (/Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at GitRepository.module.exports.GitRepository.getPathStatus (/Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/src/git-repository.js:265:22)
    at /Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/src/git-repository.js:342:26
    at Function.module.exports.Emitter.simpleDispatch (/Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1113:27)
    at TextBuffer.module.exports.TextBuffer.save (/Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Users/chen.xu/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "proton",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.5.2
language-docker, v1.1.6
language-ini, v1.16.0
markdown-preview-plus, v2.4.0
proton, v4.0.2
tree-view-git-status, v0.2.3

# Dev
No dev packages
```

**Comment by subesokun** [comment]
Hi @xuchen81, a fix for Atom 1.8 is already ongoing and will be hopefully released by this WE. Closing this issue in favor of #25
