### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by okdewit** [subesokun/atom-tree-view-git-status#30]
I think this might be related to the removal of node-git from atom/atom (https://github.com/atom/atom/pull/12167), because this error started popping up since I've upgraded to that build.

[Enter steps to reproduce below:]
1. Add project folder or remove project folder

**Atom Version**: 1.10.0-dev-0708140
**Electron Version**: 0.37.8
**System**: Linux Mint
**Thrown From**: [tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) package, v1.0.1
### Stack Trace

Uncaught TypeError: Cannot read property 'then' of undefined

```
At /home/okdewit/.atom/packages/tree-view-git-status/lib/utils.coffee:43

TypeError: Cannot read property 'then' of undefined
    at promiseWrapper (/home/okdewit/.atom/packages/tree-view-git-status/lib/utils.coffee:43:7)
    at Array.map (native)
    at Object.settle (/home/okdewit/.atom/packages/tree-view-git-status/lib/utils.coffee:50:31)
    at ProjectRepositories.module.exports.ProjectRepositories.subscribeUpdateRepositories (/home/okdewit/.atom/packages/tree-view-git-status/lib/repositories.coffee:40:18)
    at /home/okdewit/.atom/packages/tree-view-git-status/lib/repositories.coffee:16:8
    at Function.module.exports.Emitter.simpleDispatch (/usr/local/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.removePath (/usr/local/share/atom/resources/app.asar/src/project.js:296:22)
    at TreeView.module.exports.TreeView.removeProjectFolder (/home/okdewit/.atom/packages/tree-view/lib/tree-view.coffee:661:20)
    at space-pen-div.atom.commands.add.tree-view:remove-project-folder (/home/okdewit/.atom/packages/tree-view/lib/tree-view.coffee:134:49)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/local/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/local/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/local/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/local/share/atom/resources/app.asar/src/atom-environment.js:1115:28)
    at EventEmitter.outerCallback (/usr/local/share/atom/resources/app.asar/src/application-delegate.js:340:25)
    at emitThree (events.js:110:13)
    at EventEmitter.emit (events.js:188:7)
```
### Commands

```
  2x -8:51 core:close (atom-text-editor.editor.is-focused)
     -0:00.1.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "wrap-guide"
    ],
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-bootstrap3, v1.2.12 (inactive)
color-tabs, v0.1.8 (active)
color-tabs-regex, v0.2.5 (active)
compare-files, v0.6.2 (active)
composer, v0.5.0 (inactive)
git-control, v0.7.1 (inactive)
git-diff, v1.0.1 (active)
git-history, v3.2.0 (inactive)
git-plus, v5.16.2 (active)
jenkins, v0.3.5 (active)
jquery-snippets, v11.0.0 (active)
language-haml, v0.24.0 (active)
linter, v1.11.14 (active)
linter-eslint, v7.2.4 (active)
linter-haml, v1.2.1 (active)
linter-php, v1.2.0 (active)
linter-phpmd, v1.5.0 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.24.7 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-selection, v4.4.0 (active)
monokai-seti, v0.7.0 (active)
php-twig, v4.0.0 (active)
qolor, v0.2.2 (active)
save-session, v0.16.0 (active)
seti-ui, v1.3.2 (active)
syfi, v0.5.1 (inactive)
symbols-tree-view, v0.13.2 (active)
symfony-snippets, v0.3.0 (active)
todo-show, v1.6.0 (inactive)
tree-view, v0.208.1 (active)
tree-view-git-status, v1.0.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.4.0 (inactive)
one-light-ui, v1.4.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.0.1 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.240.1 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.99.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.1 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.0 (active)
language-gfm, v0.88.0 (active)
language-git, v0.14.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.1 (active)
language-less, v0.29.4 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.1 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.6 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.55.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.22.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by subesokun** [comment]
@okdewit thanks for reporting this bug. I'll try to investigate and prepare a fix for it.

**Comment by subesokun** [comment]
@okdewit If included now a fix which will prevent the error from being raised. It took me quite some time to migrate to the new async Git API and now they're removing it again... As Atom 1.10 is an alpha(?) version I'll keep an eye on it an hope they will readd the async API again or otherwise I'll get big troubles here :/
