### ISSUE TITLE
TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by james-poore** [subesokun/atom-tree-view-git-status#32]
I am having the same issue as: https://github.com/subesokun/atom-tree-view-git-status/issues/30 This seems to have come back.  Did the async Git API change again?  Although I am running an older, stable version of Atom compared to the version in the other issue.

[Enter steps to reproduce below:]
1. Enable tree-view-git-status

**Atom Version**: 1.9.2
**System**: Mac OS X 10.11.6
**Thrown From**: [tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) package, v1.1.0
### Stack Trace

Failed to activate the tree-view-git-status package

```
At Cannot read property 'then' of undefined

TypeError: Cannot read property 'then' of undefined
    at promiseWrapper (/Users/jamespoore/.atom/packages/tree-view-git-status/lib/utils.coffee:42:11)
    at Array.map (native)
    at Object.settle (/Users/jamespoore/.atom/packages/tree-view-git-status/lib/utils.coffee:48:14)
    at ProjectRepositories.module.exports.ProjectRepositories.subscribeUpdateRepositories (/Users/jamespoore/.atom/packages/tree-view-git-status/lib/repositories.coffee:38:5)
    at new ProjectRepositories (/Users/jamespoore/.atom/packages/tree-view-git-status/lib/repositories.coffee:16:61)
    at Object.module.exports.TreeViewGitStatus.toggle (/Users/jamespoore/.atom/packages/tree-view-git-status/lib/main.coffee:89:20)
    at Object.module.exports.TreeViewGitStatus.doInitPackage (/Users/jamespoore/.atom/packages/tree-view-git-status/lib/main.coffee:62:6)
    at Object.module.exports.TreeViewGitStatus.activate (/Users/jamespoore/.atom/packages/tree-view-git-status/lib/main.coffee:47:6)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:342:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:169:14)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:324:27)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -1:38.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-monokai.theme-atom-dark-ui)
```
### Config

``` json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "json-colorer",
      "git-projects"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/jamespoore/work/repos",
    "themes": [
      "atom-dark-ui",
      "atom-monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
aligner, v0.22.1 (active)
aligner-ruby, v1.5.0 (active)
an-old-hope-syntax, v0.5.0 (inactive)
atom-alignment, v0.12.1 (active)
atom-json-color, v0.4.2 (active)
atom-monokai, v0.10.4 (active)
autocomplete-ruby, v0.1.0 (active)
flatten-json, v0.1.4 (inactive)
git-checkout, v0.3.2 (active)
git-plus, v5.16.2 (inactive)
git-projects, v1.17.0 (inactive)
git-time-machine, v1.5.3 (inactive)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
json-colorer, v0.3.0 (inactive)
language-chef, v0.9.0 (active)
language-groovy, v0.6.0 (active)
linter, v1.11.14 (active)
linter-erb, v1.0.2 (active)
linter-ruby, v1.2.2 (active)
minimap, v4.24.7 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.1.1 (active)
minimap-selection, v4.4.0 (active)
monokai-dark, v1.3.0 (inactive)
monokai-extended, v0.3.0 (inactive)
monokai-shade, v0.3.5 (inactive)
monokai-slate, v0.5.0 (inactive)
pretty-json, v1.5.1 (active)
rubocop-auto-correct, v1.3.0 (inactive)
ruby-block, v0.3.5 (active)
ruby-bundler, v0.3.0 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (active)
tabs-to-spaces, v1.0.2 (active)
tree-view-git-branch, v0.1.2 (active)
tree-view-git-status, v1.1.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by subesokun** [comment]
@james-poore mhh very strange. I was testing the v1.1.0 release yesterday on Linux, Windows and OSX and also after heavy use on OSX I couldn't reproduce it. Also CI tests are looking good so far. Maybe something went wrong during installation. Could you try to uninstall the package once, restart Atom and then reinstall it? Sorry for the troubles.

**Comment by subesokun** [comment]
This project is no longer maintained as Atom and all repositories under Atom will be archived on December 15, 2022. Learn more in the [official announcement](https://github.blog/2022-06-08-sunsetting-atom/). Thank you for your interest in this project and your support!
