### ISSUE TITLE
Uncaught TypeError: Cannot read property 'customElements' of undefined

### ISSUE THREAD

**Issue by OmgImAlexis** [subesokun/atom-tree-view-git-status#53]
The git repo is `~/code/Twistly`.

[Enter steps to reproduce:]

1. `atom ~/code/Twistly/api`
2. Added `~/code/Twistly/frontend` as a project folder in tree view

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.3
**Thrown From**: [tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) package 1.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'customElements' of undefined

```
At /Users/xo/.atom/packages/tree-view-git-status/lib/treeviewui.coffee:183

TypeError: Cannot read property 'customElements' of undefined
    at TreeViewUI.module.exports.TreeViewUI.doUpdateRootNode (/packages/tree-view-git-status/lib/treeviewui.coffee:183:53)
    at TreeViewUI.module.exports.TreeViewUI.updateRoots (/packages/tree-view-git-status/lib/treeviewui.coffee:146:14)
    at TreeViewUI.module.exports.TreeViewUI.updateRootForRepo (/packages/tree-view-git-status/lib/treeviewui.coffee:173:6)
    at /packages/tree-view-git-status/lib/main.coffee:143:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at /packages/tree-view-git-status/lib/repositories.coffee:93:19
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Task.callback (/Applications/Atom.app/Contents/Resources/app/src/git-repository.js:412:1)
    at /Applications/Atom.app/Contents/Resources/app/src/task.js:67:1
    at /Applications/Atom.app/Contents/Resources/app/src/task.js:128:1
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/task.js:80:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -1:52.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-compact.seti-icons.seti-roboto.seti-animate)
     -1:18.5.0 application:add-project-folder (ol.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:07.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-compact.seti-icons.seti-roboto.seti-animate.theme-seti-syntax.theme-seti-ui)
```

### Non-Core Packages

```
autohide-tree-view 0.25.1 
busy-signal 1.4.1 
duplicate-removal 0.1.3 
editorconfig 2.2.2 
file-icons 2.1.6 
git-status 0.3.4 
intentions 1.1.2 
language-docker 1.1.8 
language-mako 0.6.0 
language-nginx 0.8.0 
language-pug 0.0.21 
language-vue 0.22.0 
linter 2.1.4 
linter-pycodestyle 2.0.2 
linter-stylelint 3.10.0 
linter-swagger 0.4.1 
linter-ui-default 1.6.0 
linter-xo 0.23.0 
multi-cursor 2.1.5 
seti-syntax 1.1.3 
seti-ui 1.8.0 
sort-lines 0.14.0 
tree-view-autoresize 2.0.0 
tree-view-git-status 1.4.0 
```

**Comment by subesokun** [comment]
Hi @OmgImAlexis, thanks for taking your time to report this issue! Since when are you getting this error message? I'll add some more sanity checks to avoid that this error appears but I've no guess so far what the root cause could be.

**Comment by OmgImAlexis** [comment]
I've only had it once and it hasn't happened since.

**Comment by OmgImAlexis** [comment]
[Enter steps to reproduce:]

Same as above.

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.3
**Thrown From**: [tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) package 1.4.0


### Stack Trace

Uncaught TypeError: Cannot read property 'customElements' of undefined

```
At /Users/xo/.atom/packages/tree-view-git-status/lib/treeviewui.coffee:183

TypeError: Cannot read property 'customElements' of undefined
    at TreeViewUI.module.exports.TreeViewUI.doUpdateRootNode (/packages/tree-view-git-status/lib/treeviewui.coffee:183:53)
    at TreeViewUI.module.exports.TreeViewUI.updateRoots (/packages/tree-view-git-status/lib/treeviewui.coffee:146:14)
    at TreeViewUI.module.exports.TreeViewUI.updateRootForRepo (/packages/tree-view-git-status/lib/treeviewui.coffee:173:6)
    at /packages/tree-view-git-status/lib/main.coffee:143:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at /packages/tree-view-git-status/lib/repositories.coffee:93:19
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Task.callback (/Applications/Atom.app/Contents/Resources/app/src/git-repository.js:412:1)
    at /Applications/Atom.app/Contents/Resources/app/src/task.js:67:1
    at /Applications/Atom.app/Contents/Resources/app/src/task.js:128:1
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/task.js:80:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:20 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-compact.seti-icons.seti-roboto.seti-animate)
     -0:14 application:add-project-folder (ol.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:05.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-compact.seti-icons.seti-roboto.seti-animate.theme-seti-syntax.theme-seti-ui)
```

### Non-Core Packages

```
autohide-tree-view 0.25.1 
busy-signal 1.4.1 
duplicate-removal 0.1.3 
editorconfig 2.2.2 
file-icons 2.1.7 
git-status 0.3.4 
intentions 1.1.2 
language-docker 1.1.8 
language-mako 0.6.0 
language-nginx 0.8.0 
language-pug 0.0.21 
language-vue 0.22.1 
linter 2.1.4 
linter-pycodestyle 2.0.2 
linter-stylelint 3.10.0 
linter-swagger 0.4.1 
linter-ui-default 1.6.0 
linter-xo 0.23.0 
multi-cursor 2.1.5 
seti-syntax 1.1.3 
seti-ui 1.8.0 
sort-lines 0.14.0 
tree-view-autoresize 2.1.0 
tree-view-git-status 1.4.0 
```

**Comment by OmgImAlexis** [comment]
[Enter steps to reproduce:]

1. Same issue again.

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.3
**Thrown From**: [tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) package 1.4.0


### Stack Trace

Uncaught TypeError: Cannot read property 'customElements' of undefined

```
At /Users/xo/.atom/packages/tree-view-git-status/lib/treeviewui.coffee:183

TypeError: Cannot read property 'customElements' of undefined
    at TreeViewUI.module.exports.TreeViewUI.doUpdateRootNode (/packages/tree-view-git-status/lib/treeviewui.coffee:183:53)
    at TreeViewUI.module.exports.TreeViewUI.updateRoots (/packages/tree-view-git-status/lib/treeviewui.coffee:146:14)
    at TreeViewUI.module.exports.TreeViewUI.updateRootForRepo (/packages/tree-view-git-status/lib/treeviewui.coffee:173:6)
    at /packages/tree-view-git-status/lib/main.coffee:143:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at /packages/tree-view-git-status/lib/repositories.coffee:93:19
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Task.callback (/Applications/Atom.app/Contents/Resources/app/src/git-repository.js:412:1)
    at /Applications/Atom.app/Contents/Resources/app/src/task.js:67:1
    at /Applications/Atom.app/Contents/Resources/app/src/task.js:128:1
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/task.js:80:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -3:17.7.0 snippets:next-tab-stop (input.hidden-input)
     -3:17.7.0 snippets:expand (input.hidden-input)
     -3:17.7.0 editor:indent (input.hidden-input)
     -3:17.5.0 core:move-down (input.hidden-input)
     -3:17.2.0 editor:move-to-first-character-of-line (input.hidden-input)
     -3:16.7.0 core:move-right (input.hidden-input)
     -3:16.4.0 core:backspace (input.hidden-input)
     -3:15.9.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -3:15.4.0 core:move-to-bottom (input.hidden-input)
     -3:14.5.0 core:select-to-top (input.hidden-input)
     -3:14.2.0 core:cut (input.hidden-input)
     -3:12.1.0 core:paste (input.hidden-input)
     -2:52.7.0 editor:consolidate-selections (input.hidden-input)
  2x -2:18.2.0 core:move-right (input.hidden-input)
     -0:21.4.0 application:add-project-folder (ol.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:07.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-compact.seti-icons.seti-roboto.seti-animate.theme-seti-syntax.theme-seti-ui)
```

### Non-Core Packages

```
autohide-tree-view 0.25.1 
busy-signal 1.4.1 
duplicate-removal 0.1.3 
editorconfig 2.2.2 
file-icons 2.1.7 
git-status 0.3.4 
intentions 1.1.2 
language-docker 1.1.8 
language-mako 0.6.0 
language-nginx 0.8.0 
language-pug 0.0.21 
language-vue 0.22.1 
linter 2.1.4 
linter-pycodestyle 2.0.2 
linter-stylelint 3.10.0 
linter-swagger 0.4.1 
linter-ui-default 1.6.0 
linter-xo 0.23.0 
multi-cursor 2.1.5 
seti-syntax 1.1.3 
seti-ui 1.8.0 
sort-lines 0.14.0 
tree-view-autoresize 2.1.0 
tree-view-git-status 1.4.0 
```

**Comment by subesokun** [comment]
This project is no longer maintained as Atom and all repositories under Atom will be archived on December 15, 2022. Learn more in the [official announcement](https://github.blog/2022-06-08-sunsetting-atom/). Thank you for your interest in this project and your support!
