### ISSUE TITLE
Failed to load the tree-view-git-status package

### ISSUE THREAD

**Issue by CruelBoy** [subesokun/atom-tree-view-git-status#55]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) package 1.4.0

### Stack Trace

Failed to load the tree-view-git-status package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.20.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.20.1/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-tree-view-git-status-master/lib/treeviewui.coffee:3:6)
    at /packages/atom-tree-view-git-status-master/lib/treeviewui.coffee:1:1)
    at /packages/atom-tree-view-git-status-master/lib/treeviewui.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.20.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-tree-view-git-status-master/lib/main.coffee:3:14)
    at /packages/atom-tree-view-git-status-master/lib/main.coffee:1:1)
    at /packages/atom-tree-view-git-status-master/lib/main.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.20.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.20.1/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:887:35)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.20.1/resources/app/src/package-manager.js:565:22)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/package-manager.js:479:25
    at Config.module.exports.Config.transact (~/AppData/Local/atom/app-1.20.1/resources/app/src/config.js:342:22)
    at PackageManager.module.exports.PackageManager.loadPackages (~/AppData/Local/atom/app-1.20.1/resources/app/src/package-manager.js:473:25)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/atom-environment.js:810:34
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
autoprefixer 3.7.1 
atom-beautify 0.30.5 
git-control 0.9.0 
atom-html-preview 0.2.2 
jshint 1.8.6 
pigments 0.40.2 
regex-railroad-diagram 0.19.4 
script 3.16.0 
atom-ternjs 0.18.3 
tree-view-git-status 1.4.0 
language-vue 0.23.1 
autoclose-html 0.24.0 
autocomplete-paths 2.11.0 
chrome-color-picker 0.8.0 
docblockr 0.11.0 
emmet 2.4.3 
file-type-icons 1.3.4 
git-log 0.4.1 
git-plus 7.9.3 
highlight-selected 0.13.1 
language-babel 2.74.2 
language-javascript-jsx 0.3.7 
last-cursor-position 0.9.2 
linter-csslint 2.0.0 
linter-eslint 8.3.2 
linter 2.2.0 
markdown-preview-plus 2.4.10 
merge-conflicts 1.4.5 
minimap 4.29.7 
open-in-browser 0.5.2 
tortoise-svn 0.5.1 
```

**Comment by subesokun** [comment]
This project is no longer maintained as Atom and all repositories under Atom will be archived on December 15, 2022. Learn more in the [official announcement](https://github.blog/2022-06-08-sunsetting-atom/). Thank you for your interest in this project and your support!
