### ISSUE TITLE
Failed to activate the svn package

### ISSUE THREAD

**Issue by stoneli88** [subesokun/atom-tree-view-git-status#6]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.2
**Thrown From**: [tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) package, v0.1.1
### Stack Trace

Failed to activate the svn package

```
At Cannot read property 'charAt' of undefined

TypeError: Cannot read property 'charAt' of undefined
  at Object.posix.isAbsolute (path.js:440:14)
  at Object.posix.normalize (path.js:422:26)
  at Object.module.exports.TreeViewGitStatus.subscribeUpdateRepositories (/Users/stoneli/.atom/packages/tree-view-git-status/lib/main.coffee:163:31)
  at /Users/stoneli/.atom/packages/tree-view-git-status/lib/main.coffee:89:10
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Project.module.exports.Project.setPaths (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:237:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/project.js:71:26
  at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:34)
  at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:29:18)
  at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:372:65)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:16)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:368:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
     -4:23.1.0 core:copy (atom-text-editor.editor.is-focused)
     -4:21.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:21 core:paste (atom-text-editor.editor.is-focused)
     -4:19.3.0 core:save (atom-text-editor.editor.is-focused)
     -3:20.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  4x -3:16 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:15.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:48.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:48.3.0 core:cancel (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "atom-material-ui",
      "wombat-light-syntax"
    ],
    "disabledPackages": [
      "jshint",
      "language-babel"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.7
atom-handlebars, v1.0.0
atom-jade, v0.3.0
atom-material-ui, v0.5.2
autocomplete-clang, v0.8.6
build, v0.40.0
color-picker, v2.0.9
css-snippets, v0.8.0
ember-snippets, v1.4.0
file-icon-supplement, v0.8.3
git-tab-status, v1.9.2
gulp-snippets, v0.6.1
javascript-snippets, v1.0.0
language-ejs, v0.2.0
language-gitignore, v0.2.0
linter-clang, v2.26.1
linter-cpplint, v0.1.4
node-debugger, v1.1.4
pigments, v0.8.3
react, v0.12.4
react-snippets, v0.1.4
set-syntax, v0.3.0
svn, v0.0.6
tree-view-git-status, v0.1.1
wombat-light-syntax, v1.1.0

# Dev
No dev packages
```

**Comment by subesokun** [comment]
@stoneli88 Thanks a lot for reporting this issue! I'll try to get a fix ready by this weekend.

**Comment by subesokun** [comment]
@stoneli88 I've fixed now the error but for now you won't see the svn status in the tree view as the atom-svn package is returning a none valid working directory for the svn repo. If they fix that issue the svn status will be shown properly. I'll open an issue for that on the atom-svn package.
