### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/atom:'

### ISSUE THREAD

**Issue by patmcd** [subesokun/atom-tree-view-git-status#9]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) package, v0.2.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/atom:'

```
At ATOM_SHELL_ASAR.js:50

Error: ENOENT: no such file or directory, lstat '/atom:'
  at Error (native)
  at fs.lstatSync (fs.js:836:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:170:16)
  at Object.realpathSync (fs.js:1439:21)
  at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:243:29)
  at Object.module.exports.TreeViewGitStatus.normalizePath (/Users/mcdowep/.atom/packages/tree-view-git-status/lib/main.coffee:293:15)
  at Object.module.exports.TreeViewGitStatus.updateRoots (/Users/mcdowep/.atom/packages/tree-view-git-status/lib/main.coffee:194:21)
  at /Users/mcdowep/.atom/packages/tree-view-git-status/lib/main.coffee:149:10
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Project.module.exports.Project.addPath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:279:29)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:41:32)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "asciidoc-preview",
      "ansible-snippets",
      "Zen",
      "foldericons-zelda",
      "git-control",
      "language-scala",
      "linter-csslint",
      "markdown-pdf",
      "preview",
      "remote-sync",
      "script",
      "tabs-to-spaces",
      "term2"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-syntax, v0.2.3
atom-material-ui, v0.6.0
autoclose-html, v0.19.0
autocomplete-paths, v1.0.2
autocomplete-python, v0.5.3
file-icons, v1.6.9
git-log, v0.4.1
highlight-line, v0.11.0
highlight-selected, v0.10.1
javascript-snippets, v1.0.0
jshint, v1.7.0
language-docker, v1.1.3
linter, v1.5.1
linter-clang, v3.2.1
linter-coffeelint, v1.1.0
linter-js-yaml, v1.1.2
linter-jshint, v1.2.0
linter-jsonlint, v1.0.1
linter-pylint, v1.0.0
linter-shellcheck, v1.0.1
minimap, v4.13.3
project-manager, v2.5.1
react, v0.12.8
trailing-spaces, v0.3.2
travis-ci-status, v0.18.0
tree-view-git-status, v0.2.0
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by subesokun** [comment]
Hi @patmcd! Thanks for reporting the bug.

Some questions, did you get this error first after upgrading to tree-view-git-status `v0.2.0`? Also does this error always appear for any project you try to load or only for a specific one? Could you also tell me the absolute path to your project folder you're trying to load and tell me if the `.git` folder is a direct child of it?

For some reason node is not able to resolve the [realpath](https://nodejs.org/api/fs.html#fs_fs_realpath_path_cache_callback) of your project :(

**Comment by subesokun** [comment]
Sorry one more thing, could you try the following and tell me the output?

``` bash
git clone https://github.com/subesokun/atom-tree-view-git-status
cd atom-tree-view-git-status
apm install
apm test
```
